### ISSUE TITLE
On clicking of the item the drawer is not closing 

### ISSUE THREAD

**Issue by AshokSongara** [yarolegovich/SlidingRootNav#17]

**Comment by Rob--** [comment]
The [documentation](https://github.com/yarolegovich/SlidingRootNav#controling-the-layout) tells you how to do this.

The nav builder returns an interface, so assign this to a variable instead of simply just calling it:
```java
SlidingRootNav slidingRootNav = new SlidingRoovNavBuilder(this)
    .withToolbarMenuToggle(toolbar)
    .withMenuOpened(true)
    .inject()
```

And then inside your `onItemSelected` event, just make a call to close the menu:
```java
@Override
public void onItemSelected(int position) {
    slidingRootNav.closeMenu(true);
}
```

**Comment by AshokSongara** [comment]
Hi Sir,

 When i'm using this code at that time getting error of casting  an
interface to activity

SlidingRootNav slidingRootNav = new SlidingRoovNavBuilder(this)
    .withToolbarMenuToggle(toolbar)
    .withMenuOpened(true)
    .inject()


so please can you send me whole code in working phase



Thanks


Regards,

Ashok

**Comment by Rob--** [comment]
Don't have working code on hand right now, but just create your `SlidingRootNav` as normal and in the same context as `this` (that you pass to your constructor (`new SlidingRootNavBuilder(this)`) add your override method for `onItemSelected`, I pasted a snippet above.
