### ISSUE TITLE
Null Pointer & IllegalState Exception

### ISSUE THREAD

**Issue by MukundPradhan** [yarolegovich/SlidingRootNav#36]
Sir,
There is a Illegal State Exception error for the setContentView for Menu (There must be a child inside menu).
& NullPointer Exception for Recycleview Layout Manager.

**Comment by yarolegovich** [comment]
Make sure that the `View` returned from `activity.findViewById(android.R.id.content)` has exactly one child.

**Comment by MasoudMHS** [comment]
hi
im a beginner in android.
i have a serious problem for days with your library

i have problem with:
        rcl.setLayoutManager( new LinearLayoutManager( MainActivity.this ) );
it says
Caused by: java.lang.NullPointerException:

rcl is not in activity_main.xml and i think thas is the problem BUT its not in your MainActivity's xml code tooo.
what should i do?
please help me
